name: microservice-app
services:
  todo-next:
    build:
      context: ${NEXT_SRC_DIR}
      dockerfile: Dockerfile.dev
    container_name: todo-next
    env_file:
      - .env.todo
    ports:
      - "${NEXT_HOST_PORT:-3000}:3000"
    volumes:
      - ${NEXT_SRC_DIR}:/workdir

  todo-express:
    build:
      context: ${EXPRESS_SERVER_SRC_DIR}
      dockerfile: Dockerfile.dev
    container_name: todo-express
    env_file:
      - .env.todo
    ports:
      - "${EXPRESS_SERVER_PORT:-3001}:3000"
      - "${EXPRESS_DEBUG_SERVER_PORT:-9229}:9229"
    volumes:
      - ${EXPRESS_SERVER_SRC_DIR}:/workdir

  todo-postgresql:
    build:
      context: dockerfiles/postgresql
      dockerfile: Dockerfile.dev
    container_name: todo-postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    env_file:
      - .env.todo
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    volumes:
      - todo_postgres_data:/var/lib/postgresql/data
      - ./dockerfiles/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf

  todo-minio:
    build:
      context: dockerfiles/minio
      dockerfile: Dockerfile.dev
    container_name: todo-minio
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    env_file:
      - .env.todo
    volumes:
      - todo_minio_data:/data

volumes:
  todo_postgres_data:
  todo_minio_data:
